// Code generated by ogen, DO NOT EDIT.

package authclient

// OperationName is the ogen operation name
type OperationName = string

const (
	ConsumeInviteOperation            OperationName = "ConsumeInvite"
	CreateCredentialOperation         OperationName = "CreateCredential"
	CreateInviteOperation             OperationName = "CreateInvite"
	DeleteCredentialOperation         OperationName = "DeleteCredential"
	MintTokenOperation                OperationName = "MintToken"
	RefreshTokenOperation             OperationName = "RefreshToken"
	RevokeTokenOperation              OperationName = "RevokeToken"
	RevokeUserTokensOperation         OperationName = "RevokeUserTokens"
	UpdateCredentialPasswordOperation OperationName = "UpdateCredentialPassword"
	ValidateCredentialOperation       OperationName = "ValidateCredential"
	ValidateTokenOperation            OperationName = "ValidateToken"
)
