// Code generated by ogen, DO NOT EDIT.

package authclient

import (
	"fmt"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

func (s *ErrorModelStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/ConsumeInviteInputBody
type ConsumeInviteInputBody struct {
	// Raw URL-safe base64 invite token from the link.
	Token string `json:"token"`
}

// GetToken returns the value of Token.
func (s *ConsumeInviteInputBody) GetToken() string {
	return s.Token
}

// SetToken sets the value of Token.
func (s *ConsumeInviteInputBody) SetToken(val string) {
	s.Token = val
}

// ConsumeInviteNoContent is response for ConsumeInvite operation.
type ConsumeInviteNoContent struct{}

// Ref: #/components/schemas/CreateCredentialInputBody
type CreateCredentialInputBody struct {
	// User email address.
	Email string `json:"email"`
	// Plaintext password; bcrypt hashed at cost 12.
	Password string `json:"password"`
}

// GetEmail returns the value of Email.
func (s *CreateCredentialInputBody) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *CreateCredentialInputBody) GetPassword() string {
	return s.Password
}

// SetEmail sets the value of Email.
func (s *CreateCredentialInputBody) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *CreateCredentialInputBody) SetPassword(val string) {
	s.Password = val
}

// Ref: #/components/schemas/CreateCredentialOutputBody
type CreateCredentialOutputBody struct {
	// UUID of the created credential.
	CredentialID string `json:"credential_id"`
}

// GetCredentialID returns the value of CredentialID.
func (s *CreateCredentialOutputBody) GetCredentialID() string {
	return s.CredentialID
}

// SetCredentialID sets the value of CredentialID.
func (s *CreateCredentialOutputBody) SetCredentialID(val string) {
	s.CredentialID = val
}

// Ref: #/components/schemas/CreateInviteInputBody
type CreateInviteInputBody struct {
	// Claims to embed (e.g. email, entity_id, entity_role).
	Claims CreateInviteInputBodyClaims `json:"claims"`
	// Credential UUID of the admin issuing the invite.
	CreatedBy string `json:"created_by"`
}

// GetClaims returns the value of Claims.
func (s *CreateInviteInputBody) GetClaims() CreateInviteInputBodyClaims {
	return s.Claims
}

// GetCreatedBy returns the value of CreatedBy.
func (s *CreateInviteInputBody) GetCreatedBy() string {
	return s.CreatedBy
}

// SetClaims sets the value of Claims.
func (s *CreateInviteInputBody) SetClaims(val CreateInviteInputBodyClaims) {
	s.Claims = val
}

// SetCreatedBy sets the value of CreatedBy.
func (s *CreateInviteInputBody) SetCreatedBy(val string) {
	s.CreatedBy = val
}

// Claims to embed (e.g. email, entity_id, entity_role).
type CreateInviteInputBodyClaims map[string]jx.Raw

func (s *CreateInviteInputBodyClaims) init() CreateInviteInputBodyClaims {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/CreateInviteOutputBody
type CreateInviteOutputBody struct {
	// Invite expiry as RFC 3339 timestamp.
	ExpiresAt string `json:"expires_at"`
	// Raw URL-safe base64 token; returned once and never stored.
	Token string `json:"token"`
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *CreateInviteOutputBody) GetExpiresAt() string {
	return s.ExpiresAt
}

// GetToken returns the value of Token.
func (s *CreateInviteOutputBody) GetToken() string {
	return s.Token
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *CreateInviteOutputBody) SetExpiresAt(val string) {
	s.ExpiresAt = val
}

// SetToken sets the value of Token.
func (s *CreateInviteOutputBody) SetToken(val string) {
	s.Token = val
}

// DeleteCredentialNoContent is response for DeleteCredential operation.
type DeleteCredentialNoContent struct{}

// Ref: #/components/schemas/ErrorDetail
type ErrorDetail struct {
	// Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'.
	Location OptString `json:"location"`
	// Error message text.
	Message OptString `json:"message"`
	// The value at the given location.
	Value jx.Raw `json:"value"`
}

// GetLocation returns the value of Location.
func (s *ErrorDetail) GetLocation() OptString {
	return s.Location
}

// GetMessage returns the value of Message.
func (s *ErrorDetail) GetMessage() OptString {
	return s.Message
}

// GetValue returns the value of Value.
func (s *ErrorDetail) GetValue() jx.Raw {
	return s.Value
}

// SetLocation sets the value of Location.
func (s *ErrorDetail) SetLocation(val OptString) {
	s.Location = val
}

// SetMessage sets the value of Message.
func (s *ErrorDetail) SetMessage(val OptString) {
	s.Message = val
}

// SetValue sets the value of Value.
func (s *ErrorDetail) SetValue(val jx.Raw) {
	s.Value = val
}

// Ref: #/components/schemas/ErrorModel
type ErrorModel struct {
	// A human-readable explanation specific to this occurrence of the problem.
	Detail OptString `json:"detail"`
	// Optional list of individual error details.
	Errors OptNilErrorDetailArray `json:"errors"`
	// A URI reference that identifies the specific occurrence of the problem.
	Instance OptURI `json:"instance"`
	// HTTP status code.
	Status OptInt64 `json:"status"`
	// A short, human-readable summary of the problem type. This value should not change between
	// occurrences of the error.
	Title OptString `json:"title"`
	// A URI reference to human-readable documentation for the error.
	Type OptURI `json:"type"`
}

// GetDetail returns the value of Detail.
func (s *ErrorModel) GetDetail() OptString {
	return s.Detail
}

// GetErrors returns the value of Errors.
func (s *ErrorModel) GetErrors() OptNilErrorDetailArray {
	return s.Errors
}

// GetInstance returns the value of Instance.
func (s *ErrorModel) GetInstance() OptURI {
	return s.Instance
}

// GetStatus returns the value of Status.
func (s *ErrorModel) GetStatus() OptInt64 {
	return s.Status
}

// GetTitle returns the value of Title.
func (s *ErrorModel) GetTitle() OptString {
	return s.Title
}

// GetType returns the value of Type.
func (s *ErrorModel) GetType() OptURI {
	return s.Type
}

// SetDetail sets the value of Detail.
func (s *ErrorModel) SetDetail(val OptString) {
	s.Detail = val
}

// SetErrors sets the value of Errors.
func (s *ErrorModel) SetErrors(val OptNilErrorDetailArray) {
	s.Errors = val
}

// SetInstance sets the value of Instance.
func (s *ErrorModel) SetInstance(val OptURI) {
	s.Instance = val
}

// SetStatus sets the value of Status.
func (s *ErrorModel) SetStatus(val OptInt64) {
	s.Status = val
}

// SetTitle sets the value of Title.
func (s *ErrorModel) SetTitle(val OptString) {
	s.Title = val
}

// SetType sets the value of Type.
func (s *ErrorModel) SetType(val OptURI) {
	s.Type = val
}

// ErrorModelStatusCode wraps ErrorModel with StatusCode.
type ErrorModelStatusCode struct {
	StatusCode int
	Response   ErrorModel
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorModelStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorModelStatusCode) GetResponse() ErrorModel {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorModelStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorModelStatusCode) SetResponse(val ErrorModel) {
	s.Response = val
}

// Ref: #/components/schemas/MintTokenInputBody
type MintTokenInputBody struct {
	// Opaque claims set by veloci-api; stored verbatim.
	Claims MintTokenInputBodyClaims `json:"claims"`
	// UUID of the credential to bind this token to.
	CredentialID string `json:"credential_id"`
}

// GetClaims returns the value of Claims.
func (s *MintTokenInputBody) GetClaims() MintTokenInputBodyClaims {
	return s.Claims
}

// GetCredentialID returns the value of CredentialID.
func (s *MintTokenInputBody) GetCredentialID() string {
	return s.CredentialID
}

// SetClaims sets the value of Claims.
func (s *MintTokenInputBody) SetClaims(val MintTokenInputBodyClaims) {
	s.Claims = val
}

// SetCredentialID sets the value of CredentialID.
func (s *MintTokenInputBody) SetCredentialID(val string) {
	s.CredentialID = val
}

// Opaque claims set by veloci-api; stored verbatim.
type MintTokenInputBodyClaims map[string]jx.Raw

func (s *MintTokenInputBodyClaims) init() MintTokenInputBodyClaims {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilErrorDetailArray returns new OptNilErrorDetailArray with value set to v.
func NewOptNilErrorDetailArray(v []ErrorDetail) OptNilErrorDetailArray {
	return OptNilErrorDetailArray{
		Value: v,
		Set:   true,
	}
}

// OptNilErrorDetailArray is optional nullable []ErrorDetail.
type OptNilErrorDetailArray struct {
	Value []ErrorDetail
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilErrorDetailArray was set.
func (o OptNilErrorDetailArray) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilErrorDetailArray) Reset() {
	var v []ErrorDetail
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilErrorDetailArray) SetTo(v []ErrorDetail) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilErrorDetailArray) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilErrorDetailArray) SetToNull() {
	o.Set = true
	o.Null = true
	var v []ErrorDetail
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilErrorDetailArray) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilErrorDetailArray) Get() (v []ErrorDetail, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilErrorDetailArray) Or(d []ErrorDetail) []ErrorDetail {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptURI returns new OptURI with value set to v.
func NewOptURI(v url.URL) OptURI {
	return OptURI{
		Value: v,
		Set:   true,
	}
}

// OptURI is optional url.URL.
type OptURI struct {
	Value url.URL
	Set   bool
}

// IsSet returns true if OptURI was set.
func (o OptURI) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptURI) Reset() {
	var v url.URL
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptURI) SetTo(v url.URL) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptURI) Get() (v url.URL, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptURI) Or(d url.URL) url.URL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/RefreshTokenInputBody
type RefreshTokenInputBody struct {
	// The refresh JWT to exchange for a new pair.
	RefreshToken string `json:"refresh_token"`
}

// GetRefreshToken returns the value of RefreshToken.
func (s *RefreshTokenInputBody) GetRefreshToken() string {
	return s.RefreshToken
}

// SetRefreshToken sets the value of RefreshToken.
func (s *RefreshTokenInputBody) SetRefreshToken(val string) {
	s.RefreshToken = val
}

// RevokeTokenNoContent is response for RevokeToken operation.
type RevokeTokenNoContent struct{}

// RevokeUserTokensNoContent is response for RevokeUserTokens operation.
type RevokeUserTokensNoContent struct{}

// Ref: #/components/schemas/TokenPairOutputBody
type TokenPairOutputBody struct {
	// Signed HS256 JWT; valid for session.access_token_ttl_minutes.
	AccessToken string `json:"access_token"`
	// Access token expiry as RFC 3339 timestamp.
	ExpiresAt string `json:"expires_at"`
	// Access token lifetime in seconds.
	ExpiresIn int64 `json:"expires_in"`
	// JTI of the access token.
	Jti string `json:"jti"`
	// Signed HS256 JWT; valid for session.refresh_token_ttl_hours.
	RefreshToken string `json:"refresh_token"`
}

// GetAccessToken returns the value of AccessToken.
func (s *TokenPairOutputBody) GetAccessToken() string {
	return s.AccessToken
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *TokenPairOutputBody) GetExpiresAt() string {
	return s.ExpiresAt
}

// GetExpiresIn returns the value of ExpiresIn.
func (s *TokenPairOutputBody) GetExpiresIn() int64 {
	return s.ExpiresIn
}

// GetJti returns the value of Jti.
func (s *TokenPairOutputBody) GetJti() string {
	return s.Jti
}

// GetRefreshToken returns the value of RefreshToken.
func (s *TokenPairOutputBody) GetRefreshToken() string {
	return s.RefreshToken
}

// SetAccessToken sets the value of AccessToken.
func (s *TokenPairOutputBody) SetAccessToken(val string) {
	s.AccessToken = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *TokenPairOutputBody) SetExpiresAt(val string) {
	s.ExpiresAt = val
}

// SetExpiresIn sets the value of ExpiresIn.
func (s *TokenPairOutputBody) SetExpiresIn(val int64) {
	s.ExpiresIn = val
}

// SetJti sets the value of Jti.
func (s *TokenPairOutputBody) SetJti(val string) {
	s.Jti = val
}

// SetRefreshToken sets the value of RefreshToken.
func (s *TokenPairOutputBody) SetRefreshToken(val string) {
	s.RefreshToken = val
}

// Ref: #/components/schemas/UpdateCredentialPasswordInputBody
type UpdateCredentialPasswordInputBody struct {
	// New plaintext password.
	Password string `json:"password"`
}

// GetPassword returns the value of Password.
func (s *UpdateCredentialPasswordInputBody) GetPassword() string {
	return s.Password
}

// SetPassword sets the value of Password.
func (s *UpdateCredentialPasswordInputBody) SetPassword(val string) {
	s.Password = val
}

// UpdateCredentialPasswordNoContent is response for UpdateCredentialPassword operation.
type UpdateCredentialPasswordNoContent struct{}

// Ref: #/components/schemas/ValidateCredentialInputBody
type ValidateCredentialInputBody struct {
	// User email address.
	Email string `json:"email"`
	// Plaintext password.
	Password string `json:"password"`
}

// GetEmail returns the value of Email.
func (s *ValidateCredentialInputBody) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *ValidateCredentialInputBody) GetPassword() string {
	return s.Password
}

// SetEmail sets the value of Email.
func (s *ValidateCredentialInputBody) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *ValidateCredentialInputBody) SetPassword(val string) {
	s.Password = val
}

// Ref: #/components/schemas/ValidateCredentialOutputBody
type ValidateCredentialOutputBody struct {
	// Credential UUID used as token subject.
	CredentialID string                                 `json:"credential_id"`
	SystemRole   ValidateCredentialOutputBodySystemRole `json:"system_role"`
}

// GetCredentialID returns the value of CredentialID.
func (s *ValidateCredentialOutputBody) GetCredentialID() string {
	return s.CredentialID
}

// GetSystemRole returns the value of SystemRole.
func (s *ValidateCredentialOutputBody) GetSystemRole() ValidateCredentialOutputBodySystemRole {
	return s.SystemRole
}

// SetCredentialID sets the value of CredentialID.
func (s *ValidateCredentialOutputBody) SetCredentialID(val string) {
	s.CredentialID = val
}

// SetSystemRole sets the value of SystemRole.
func (s *ValidateCredentialOutputBody) SetSystemRole(val ValidateCredentialOutputBodySystemRole) {
	s.SystemRole = val
}

type ValidateCredentialOutputBodySystemRole string

const (
	ValidateCredentialOutputBodySystemRoleServerAdmin ValidateCredentialOutputBodySystemRole = "server_admin"
	ValidateCredentialOutputBodySystemRoleUser        ValidateCredentialOutputBodySystemRole = "user"
)

// AllValues returns all ValidateCredentialOutputBodySystemRole values.
func (ValidateCredentialOutputBodySystemRole) AllValues() []ValidateCredentialOutputBodySystemRole {
	return []ValidateCredentialOutputBodySystemRole{
		ValidateCredentialOutputBodySystemRoleServerAdmin,
		ValidateCredentialOutputBodySystemRoleUser,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ValidateCredentialOutputBodySystemRole) MarshalText() ([]byte, error) {
	switch s {
	case ValidateCredentialOutputBodySystemRoleServerAdmin:
		return []byte(s), nil
	case ValidateCredentialOutputBodySystemRoleUser:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ValidateCredentialOutputBodySystemRole) UnmarshalText(data []byte) error {
	switch ValidateCredentialOutputBodySystemRole(data) {
	case ValidateCredentialOutputBodySystemRoleServerAdmin:
		*s = ValidateCredentialOutputBodySystemRoleServerAdmin
		return nil
	case ValidateCredentialOutputBodySystemRoleUser:
		*s = ValidateCredentialOutputBodySystemRoleUser
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ValidateTokenInputBody
type ValidateTokenInputBody struct {
	// Raw token — JWT (three dot-separated base64url segments) or OTU (flat base64url).
	Token string `json:"token"`
}

// GetToken returns the value of Token.
func (s *ValidateTokenInputBody) GetToken() string {
	return s.Token
}

// SetToken sets the value of Token.
func (s *ValidateTokenInputBody) SetToken(val string) {
	s.Token = val
}

// Ref: #/components/schemas/ValidateTokenOutputBody
type ValidateTokenOutputBody struct {
	// Opaque claims from storage; DB-authoritative.
	Claims ValidateTokenOutputBodyClaims `json:"claims"`
	// Credential UUID. Present only when token_type is access.
	CredentialID OptString `json:"credential_id"`
	// Access token JTI. Present only when token_type is access.
	Jti OptString `json:"jti"`
	// Token type from the validated record.
	TokenType ValidateTokenOutputBodyTokenType `json:"token_type"`
}

// GetClaims returns the value of Claims.
func (s *ValidateTokenOutputBody) GetClaims() ValidateTokenOutputBodyClaims {
	return s.Claims
}

// GetCredentialID returns the value of CredentialID.
func (s *ValidateTokenOutputBody) GetCredentialID() OptString {
	return s.CredentialID
}

// GetJti returns the value of Jti.
func (s *ValidateTokenOutputBody) GetJti() OptString {
	return s.Jti
}

// GetTokenType returns the value of TokenType.
func (s *ValidateTokenOutputBody) GetTokenType() ValidateTokenOutputBodyTokenType {
	return s.TokenType
}

// SetClaims sets the value of Claims.
func (s *ValidateTokenOutputBody) SetClaims(val ValidateTokenOutputBodyClaims) {
	s.Claims = val
}

// SetCredentialID sets the value of CredentialID.
func (s *ValidateTokenOutputBody) SetCredentialID(val OptString) {
	s.CredentialID = val
}

// SetJti sets the value of Jti.
func (s *ValidateTokenOutputBody) SetJti(val OptString) {
	s.Jti = val
}

// SetTokenType sets the value of TokenType.
func (s *ValidateTokenOutputBody) SetTokenType(val ValidateTokenOutputBodyTokenType) {
	s.TokenType = val
}

// Opaque claims from storage; DB-authoritative.
type ValidateTokenOutputBodyClaims map[string]jx.Raw

func (s *ValidateTokenOutputBodyClaims) init() ValidateTokenOutputBodyClaims {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Token type from the validated record.
type ValidateTokenOutputBodyTokenType string

const (
	ValidateTokenOutputBodyTokenTypeAccess ValidateTokenOutputBodyTokenType = "access"
	ValidateTokenOutputBodyTokenTypeInvite ValidateTokenOutputBodyTokenType = "invite"
)

// AllValues returns all ValidateTokenOutputBodyTokenType values.
func (ValidateTokenOutputBodyTokenType) AllValues() []ValidateTokenOutputBodyTokenType {
	return []ValidateTokenOutputBodyTokenType{
		ValidateTokenOutputBodyTokenTypeAccess,
		ValidateTokenOutputBodyTokenTypeInvite,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ValidateTokenOutputBodyTokenType) MarshalText() ([]byte, error) {
	switch s {
	case ValidateTokenOutputBodyTokenTypeAccess:
		return []byte(s), nil
	case ValidateTokenOutputBodyTokenTypeInvite:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ValidateTokenOutputBodyTokenType) UnmarshalText(data []byte) error {
	switch ValidateTokenOutputBodyTokenType(data) {
	case ValidateTokenOutputBodyTokenTypeAccess:
		*s = ValidateTokenOutputBodyTokenTypeAccess
		return nil
	case ValidateTokenOutputBodyTokenTypeInvite:
		*s = ValidateTokenOutputBodyTokenTypeInvite
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
