services:
  postgres:
    ports:
      - "5432:5432"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile.dev
    command: air
    ports:
      - "8081:8081"
    volumes:
      - ./services/auth:/app
      - auth-go-cache:/root/go/pkg/mod

  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.dev
    command: air
    environment:
      - VELOCI_DEV=true
    volumes:
      - ./services/web:/app
      - veloci-go-cache:/root/go/pkg/mod

  engine:
    build:
      context: ./services/engine
      dockerfile: Dockerfile.dev
    command: cargo watch -x run
    volumes:
      - ./services/engine:/app
      - engine-cargo-registry:/usr/local/cargo/registry
      - engine-target:/app/target

volumes:
  auth-go-cache:
  veloci-go-cache:
  engine-cargo-registry:
  engine-target:
