services:
  veloci-auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile.dev
    command: air
    volumes:
      - ./services/auth:/app
      - auth-go-cache:/root/go/pkg/mod

  api:
    build:
      context: ./services/veloci
      dockerfile: Dockerfile.dev
    command: air
    volumes:
      - ./services/veloci:/app
      - veloci-go-cache:/root/go/pkg/mod

  veloci-engine:
    build:
      context: ./services/engine
      dockerfile: Dockerfile.dev
    command: cargo watch -x run
    volumes:
      - ./services/engine:/app
      - engine-cargo-registry:/usr/local/cargo/registry
      - engine-target:/app/target

volumes:
  auth-go-cache:
  veloci-go-cache:
  engine-cargo-registry:
  engine-target:
