[build]
  pre_cmd    = ["templ generate"]
  cmd        = "go build -o ./tmp/veloci ."
  bin        = "./tmp/veloci"
  args_bin   = ["serve"]
  include_ext = ["go", "templ", "toml", "css"]
  exclude_dir = ["tmp", "static"]
  delay      = 500
  poll       = true
  poll_interval = 1000

[log]
  time = false

[color]
  main = "magenta"
