// Code generated by ogen, DO NOT EDIT.

package authclient

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ConsumeInvite implements consume-invite operation.
	//
	// Sets accepted_at only if unconsumed. This is the commit point in the invite saga.
	//
	// POST /invite/consume
	ConsumeInvite(ctx context.Context, req *ConsumeInviteInputBody) error
	// CreateCredential implements create-credential operation.
	//
	// Create a new credential.
	//
	// POST /credentials/create
	CreateCredential(ctx context.Context, req *CreateCredentialInputBody) (*CreateCredentialOutputBody, error)
	// CreateInvite implements create-invite operation.
	//
	// The raw token is returned once and never stored. TTL from invite.ttl_hours in config (default 72h).
	//
	// POST /invite
	CreateInvite(ctx context.Context, req *CreateInviteInputBody) (*CreateInviteOutputBody, error)
	// DeleteCredential implements delete-credential operation.
	//
	// Permanently remove a credential and cascade tokens.
	//
	// DELETE /credentials/{id}
	DeleteCredential(ctx context.Context, params DeleteCredentialParams) error
	// MintToken implements mint-token operation.
	//
	// Mint an access+refresh token pair.
	//
	// POST /tokens/mint
	MintToken(ctx context.Context, req *MintTokenInputBody) (*TokenPairOutputBody, error)
	// RefreshToken implements refresh-token operation.
	//
	// Rotates the refresh token within a 30-second grace window to handle concurrent requests.
	//
	// POST /tokens/refresh
	RefreshToken(ctx context.Context, req *RefreshTokenInputBody) (*TokenPairOutputBody, error)
	// RevokeToken implements revoke-token operation.
	//
	// Revoke a single token by JTI (idempotent).
	//
	// DELETE /tokens/{jti}
	RevokeToken(ctx context.Context, params RevokeTokenParams) error
	// RevokeUserTokens implements revoke-user-tokens operation.
	//
	// Revoke all sessions for a credential without deleting it.
	//
	// DELETE /tokens/user/{credential_id}
	RevokeUserTokens(ctx context.Context, params RevokeUserTokensParams) error
	// UpdateCredentialPassword implements update-credential-password operation.
	//
	// Update password hash for a credential.
	//
	// PUT /credentials/{id}/password
	UpdateCredentialPassword(ctx context.Context, req *UpdateCredentialPasswordInputBody, params UpdateCredentialPasswordParams) error
	// ValidateCredential implements validate-credential operation.
	//
	// Validate email/password credentials.
	//
	// POST /credentials/validate
	ValidateCredential(ctx context.Context, req *ValidateCredentialInputBody) (*ValidateCredentialOutputBody, error)
	// ValidateToken implements validate-token operation.
	//
	// Auth detects token type by structure (JWT = two dots; OTU = no dots) and queries the appropriate
	// table.
	//
	// POST /tokens/validate
	ValidateToken(ctx context.Context, req *ValidateTokenInputBody) (*ValidateTokenOutputBody, error)
	// NewError creates *ErrorModelStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorModelStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
