// Code generated by ogen, DO NOT EDIT.

package authclient

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// DeleteCredentialParams is parameters of delete-credential operation.
type DeleteCredentialParams struct {
	// Credential UUID.
	ID string
}

func unpackDeleteCredentialParams(packed middleware.Parameters) (params DeleteCredentialParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(string)
	}
	return params
}

func decodeDeleteCredentialParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteCredentialParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// RevokeTokenParams is parameters of revoke-token operation.
type RevokeTokenParams struct {
	// Token JTI.
	Jti string
}

func unpackRevokeTokenParams(packed middleware.Parameters) (params RevokeTokenParams) {
	{
		key := middleware.ParameterKey{
			Name: "jti",
			In:   "path",
		}
		params.Jti = packed[key].(string)
	}
	return params
}

func decodeRevokeTokenParams(args [1]string, argsEscaped bool, r *http.Request) (params RevokeTokenParams, _ error) {
	// Decode path: jti.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "jti",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Jti = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "jti",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// RevokeUserTokensParams is parameters of revoke-user-tokens operation.
type RevokeUserTokensParams struct {
	// Credential UUID.
	CredentialID string
}

func unpackRevokeUserTokensParams(packed middleware.Parameters) (params RevokeUserTokensParams) {
	{
		key := middleware.ParameterKey{
			Name: "credential_id",
			In:   "path",
		}
		params.CredentialID = packed[key].(string)
	}
	return params
}

func decodeRevokeUserTokensParams(args [1]string, argsEscaped bool, r *http.Request) (params RevokeUserTokensParams, _ error) {
	// Decode path: credential_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "credential_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.CredentialID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "credential_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateCredentialPasswordParams is parameters of update-credential-password operation.
type UpdateCredentialPasswordParams struct {
	// Credential UUID.
	ID string
}

func unpackUpdateCredentialPasswordParams(packed middleware.Parameters) (params UpdateCredentialPasswordParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(string)
	}
	return params
}

func decodeUpdateCredentialPasswordParams(args [1]string, argsEscaped bool, r *http.Request) (params UpdateCredentialPasswordParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
