// Code generated by ogen, DO NOT EDIT.

package authclient

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ConsumeInvite implements consume-invite operation.
//
// Sets accepted_at only if unconsumed. This is the commit point in the invite saga.
//
// POST /invite/consume
func (UnimplementedHandler) ConsumeInvite(ctx context.Context, req *ConsumeInviteInputBody) error {
	return ht.ErrNotImplemented
}

// CreateCredential implements create-credential operation.
//
// Create a new credential.
//
// POST /credentials/create
func (UnimplementedHandler) CreateCredential(ctx context.Context, req *CreateCredentialInputBody) (r *CreateCredentialOutputBody, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateInvite implements create-invite operation.
//
// The raw token is returned once and never stored. TTL from invite.ttl_hours in config (default 72h).
//
// POST /invite
func (UnimplementedHandler) CreateInvite(ctx context.Context, req *CreateInviteInputBody) (r *CreateInviteOutputBody, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteCredential implements delete-credential operation.
//
// Permanently remove a credential and cascade tokens.
//
// DELETE /credentials/{id}
func (UnimplementedHandler) DeleteCredential(ctx context.Context, params DeleteCredentialParams) error {
	return ht.ErrNotImplemented
}

// MintToken implements mint-token operation.
//
// Mint an access+refresh token pair.
//
// POST /tokens/mint
func (UnimplementedHandler) MintToken(ctx context.Context, req *MintTokenInputBody) (r *TokenPairOutputBody, _ error) {
	return r, ht.ErrNotImplemented
}

// RefreshToken implements refresh-token operation.
//
// Rotates the refresh token within a 30-second grace window to handle concurrent requests.
//
// POST /tokens/refresh
func (UnimplementedHandler) RefreshToken(ctx context.Context, req *RefreshTokenInputBody) (r *TokenPairOutputBody, _ error) {
	return r, ht.ErrNotImplemented
}

// RevokeToken implements revoke-token operation.
//
// Revoke a single token by JTI (idempotent).
//
// DELETE /tokens/{jti}
func (UnimplementedHandler) RevokeToken(ctx context.Context, params RevokeTokenParams) error {
	return ht.ErrNotImplemented
}

// RevokeUserTokens implements revoke-user-tokens operation.
//
// Revoke all sessions for a credential without deleting it.
//
// DELETE /tokens/user/{credential_id}
func (UnimplementedHandler) RevokeUserTokens(ctx context.Context, params RevokeUserTokensParams) error {
	return ht.ErrNotImplemented
}

// UpdateCredentialPassword implements update-credential-password operation.
//
// Update password hash for a credential.
//
// PUT /credentials/{id}/password
func (UnimplementedHandler) UpdateCredentialPassword(ctx context.Context, req *UpdateCredentialPasswordInputBody, params UpdateCredentialPasswordParams) error {
	return ht.ErrNotImplemented
}

// ValidateCredential implements validate-credential operation.
//
// Validate email/password credentials.
//
// POST /credentials/validate
func (UnimplementedHandler) ValidateCredential(ctx context.Context, req *ValidateCredentialInputBody) (r *ValidateCredentialOutputBody, _ error) {
	return r, ht.ErrNotImplemented
}

// ValidateToken implements validate-token operation.
//
// Auth detects token type by structure (JWT = two dots; OTU = no dots) and queries the appropriate
// table.
//
// POST /tokens/validate
func (UnimplementedHandler) ValidateToken(ctx context.Context, req *ValidateTokenInputBody) (r *ValidateTokenOutputBody, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorModelStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorModelStatusCode) {
	r = new(ErrorModelStatusCode)
	return r
}
